spring:
  rabbitmq:
    username: fdxkzhhz
    password: LEUeKykyuwAzwab8-DoXLzQUf9REis4G
    host: dingo-01.rmq.cloudamqp.com
    virtual-host: fdxkzhhz

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

    jpa:
      hibernate:
        # 소비하는 쪽이므로 SQLite를 실행하면 안된다.
        ddl-auto: none
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      show-sql: true